# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(max_length=256, verbose_name=b'Question')),
                ('answer', models.TextField(max_length=512, verbose_name=b'Answer')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='developer',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='developer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='developer_title',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='qanda',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Developer'),
        ),
    ]
