# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180804_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['developer_id']},
        ),
        migrations.RemoveField(
            model_name='qanda',
            name='developer',
        ),
        migrations.AddField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default=django.utils.timezone.now, help_text=b'Please give yourself a unique Developer ID, using 16 characters or fewer.', max_length=16, unique=True, verbose_name=b'Developer ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qanda',
            name='developer_id',
            field=models.CharField(default=datetime.datetime(2018, 8, 4, 22, 58, 37, 216563, tzinfo=utc), help_text=b'Please give your unique 16 character developer ID to ensure this QandA is saved to your developer profile.', max_length=16, verbose_name=b'Developer ID'),
            preserve_default=False,
        ),
    ]
