# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 00:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180804_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_id',
            field=models.CharField(default=datetime.datetime.now, help_text=b'Please give yourself a unique Developer ID, using 16 characters or fewer.', max_length=16, unique=True, verbose_name=b'Developer ID'),
        ),
    ]
