# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-05 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180804_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='github',
            field=models.CharField(blank=True, max_length=32, verbose_name=b'GitHub UserName'),
        ),
        migrations.AddField(
            model_name='developer',
            name='linkedin',
            field=models.CharField(blank=True, max_length=32, verbose_name=b'LinkedIn UserName'),
        ),
    ]
